version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Nesbytnov
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_net

  python:
    image: python:3.11-slim
    container_name: python_app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=Nesbytnov
      - DB_USER=postgres
      - DB_PASSWORD=12345678
    depends_on:
      - db
    networks:
      - app_net
    command: |
      bash -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      python /app/main.py
      "
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: on-failure

networks:
  app_net:
    driver: bridge
